import type { Letter } from '../types/letter';

const letter: Letter = {
  year: 1979,
  title: 'Inflation: The Invisible Tax',
  subtitle: 'The Tapeworm Thesis, Pricing Power, and True Economic Earnings',
  paragraphs: [
    {
      en: 'Berkshire Hathaway\'s operating earnings improved substantially in 1979, but I would rather discuss a subject that I believe is of far greater long-term importance to every shareholder: inflation. Over the past decade, the purchasing power of the American dollar has declined by more than half. This relentless erosion of value is not an accident or a natural phenomenon. It is the direct result of government policies that have consistently spent more than they collect and financed the difference through monetary expansion. Inflation is a tax on capital, a tax on savings, and a tax on the prudent. It is the most important economic issue of our time, yet it is seldom discussed with the candor it deserves.',
      zh: '伯克希尔·哈撒韦1979年的经营收益大幅改善，但我更想讨论一个我认为对每位股东的长远利益都更为重要的议题：通货膨胀。在过去十年中，美元的购买力已经下降了超过一半。这种价值的无情侵蚀并非意外或自然现象。这是政府政策直接导致的结果，这些政策一贯支出超过收入，并通过货币扩张来弥补差额。通货膨胀是对资本的征税、对储蓄的征税、对谨慎者的征税。它是我们这个时代最重要的经济议题，却很少以应有的坦诚来讨论。',
    },
    {
      en: 'I have come to think of inflation as a gigantic corporate tapeworm. That tapeworm preemptively consumes its requisite daily diet of investment dollars regardless of the health of the host organization. Whatever the level of reported profits — even if they are zero — the tapeworm of inflation demands more capital merely to maintain the same unit volume of business. Depreciation charges, which are based on historical costs, are insufficient to replace assets at current inflated prices. The result is that reported earnings systematically overstate true economic earnings, and the tax code compounds the problem by taxing these illusory profits as if they were real.',
      zh: '我逐渐将通货膨胀视为一条巨大的企业绦虫。这条绦虫不管宿主组织的健康状况如何，都会预先吞食其每日所需的投资资金。无论报告的利润水平如何——即使为零——通货膨胀的绦虫也需要更多的资本，仅仅是为了维持相同的业务量。基于历史成本的折旧费用不足以按当前通胀后的价格来替换资产。结果是报告的盈利系统地高估了真正的经济盈利，而税法又将这些虚幻的利润当作真实的来征税，进一步加剧了问题。',
    },
    {
      en: 'The best protection against inflation, we have found, is to own businesses that possess two characteristics: first, an ability to increase prices rather easily — even when product demand is flat and capacity is not fully utilized — without fear of significant loss of either market share or unit volume; and second, an ability to accommodate large dollar volume increases in business — often generated more by inflation than by real growth — with only minor additional investment of capital. See\'s Candy possesses both of these attributes in abundance, which is why it is such a valuable asset in an inflationary world.',
      zh: '我们发现，对抗通货膨胀的最佳保护是拥有具备两个特征的企业：第一，能够相当容易地提高价格——即使产品需求平淡、产能未充分利用——而无需担心市场份额或销售量的显著损失；第二，能够以仅需少量额外资本投入的方式，适应业务中因通货膨胀（而非实际增长）而产生的大额美元销售额增长。喜诗糖果大量地拥有这两个特征，这就是为什么在通货膨胀的世界里它是一笔如此宝贵的资产。',
    },
    {
      en: 'Let me illustrate the distinction between a business that can cope with inflation and one that cannot. In 1979, See\'s Candy earned approximately $7.5 million pre-tax on tangible net assets of about $15 million — a return of 50%. If inflation doubled all of its costs and prices overnight — wages, ingredients, rent, and selling prices — See\'s would require roughly $15 million more in capital to finance the same physical volume of business. But if See\'s can simply raise its prices to compensate, it can earn $15 million on $30 million of net assets — the same 50% return. The business does not need to grow in real terms; it merely needs to keep pace with inflation to maintain its high return on capital.',
      zh: '让我举例说明能够应对通货膨胀的企业与不能应对的企业之间的区别。1979年，喜诗糖果在约1500万美元的有形净资产上赚取了约750万美元的税前利润——回报率为50%。如果通货膨胀一夜之间将其所有成本和价格翻倍——工资、原料、租金和售价——喜诗将需要额外约1500万美元的资本来支持相同实物量的业务。但如果喜诗能够简单地提高价格来补偿，它可以在3000万美元的净资产上赚取1500万美元——仍然是50%的回报率。这家企业不需要实际增长；它只需要跟上通货膨胀的步伐，就能维持其高资本回报率。',
    },
    {
      en: 'Now consider the contrast with a business like our textile operation. In this industry, excess capacity and intense price competition mean that individual companies have virtually no ability to raise prices in response to cost increases. The result is a profit squeeze that compounds year after year. Furthermore, the capital required to replace worn-out equipment rises inexorably with inflation, while the earnings generated by that equipment stagnate. This is the inflationary trap in its most unforgiving form. The textile business requires ever-increasing amounts of capital and produces ever-decreasing returns on that capital — a formula for the gradual destruction of shareholder value.',
      zh: '现在考虑一下与我们纺织业务这样的企业的对比。在这个行业，产能过剩和激烈的价格竞争意味着单个公司几乎没有任何能力通过提高价格来应对成本上涨。结果就是利润年复一年地被压缩。此外，更换陈旧设备所需的资本随着通货膨胀不可阻挡地上升，而该设备产生的收益却停滞不前。这就是最无情的通货膨胀陷阱。纺织业务需要不断增加的资本，却对该资本产生不断递减的回报——这是股东价值逐渐被摧毁的配方。',
    },
    {
      en: 'Our insurance operations had a mixed year in 1979. The combined underwriting ratio for our insurance group was approximately 101%, meaning we paid slightly more than a dollar in claims and expenses for every dollar of premium we received. This is a disappointment, but it must be viewed in context: the industry as a whole reported underwriting ratios significantly worse than ours. We continued to benefit from our insistence on underwriting discipline and from the outstanding management of our key insurance subsidiaries. The float continued to grow, and the cost of that float — while not zero this year — remained far below what we would have paid for any alternative source of capital.',
      zh: '我们的保险业务在1979年表现参差不齐。我们保险集团的综合承保比率约为101%，这意味着我们为收到的每一美元保费支付了略微超过一美元的赔款和费用。这令人失望，但必须放在背景下看：整个行业报告的承保比率比我们差得多。我们继续受益于我们坚持承保纪律以及主要保险子公司出色的管理。浮存金继续增长，而浮存金的成本——虽然不是今年为零——仍然远低于我们为任何其他资本来源所支付的费用。',
    },
    {
      en: 'I want to conclude with a few thoughts on book value. Many investors and analysts focus heavily on book value per share as a measure of corporate progress. While book value is a useful starting point, it is an accounting construct that can diverge dramatically from true economic value. A business like See\'s Candy is worth vastly more than its book value because of the intangible earning power that is not captured on the balance sheet. Conversely, a business like our textile division may be worth less than its book value because the earnings it generates are insufficient to justify the capital employed. The question that matters is not "What is the book value?" but "What is the earning power that can be generated on the assets employed?"',
      zh: '我想以对账面价值的一些思考来结束。许多投资者和分析师高度关注每股账面价值，将其作为衡量公司进展的指标。虽然账面价值是一个有用的起点，但它是一个会计构造，可能与真实经济价值存在巨大差异。像喜诗糖果这样的企业，其价值远远超过其账面价值，因为其资产负债表未能体现的无形盈利能力。相反，像我们纺织部门这样的企业，其价值可能低于其账面价值，因为它产生的收益不足以证明所使用资本的合理性。重要的问题不是"账面价值是多少？"，而是"所用资产能够产生什么样的盈利能力？"',
    },
  ],
};

export default letter;
